# Generated by Django 4.0.3 on 2022-04-13 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admittance', '0002_admittance_title_chronicillness_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chronicillness',
            options={'ordering': ['-id'], 'verbose_name': 'Chronic illnes', 'verbose_name_plural': 'Chronic illnes'},
        ),
    ]
